version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.local
    container_name: chat-backend
    command: yarn start:dev
    ports:
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      # Mount toàn bộ code, trừ node_modules
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    image: postgres:16
    container_name: chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nguyentran
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat-redis
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  pgdata:
