version: '3.8'

services:
  backend:
    build: .
    container_name: chat-backend
    ports:
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:16
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: nguyentran
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat-redis
    ports:
      - '6379:6379'
    restart: always

volumes:
  pgdata:
